import{a as d,S as m,i as h}from"./assets/vendor-1d5366ac.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function c(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=c(e);fetch(e.href,o)}})();const g="live_Zuu1PB5DCXr8IC90o7QvjqwUwjyaEDC5Biv1MSecsCZxv5jxKZHuSX5mZ2ZjZp62",f="https://api.thecatapi.com/v1",y=`${f}/breeds`,b=`${f}/images/search`;d.defaults.headers.common["x-api-key"]=g;function S(){return d.get(`${y}`).then(t=>t.data).catch(t=>console.error(t))}function $(t){return d.get(`${b}?breed_ids=${t}`).then(r=>r.data).catch(r=>console.error(r))}const i=document.querySelector(".breed-select"),l=document.querySelector(".loader"),a=document.querySelector(".cat-info");function n(t,r){t.classList.toggle("ss-hidden",!r)}function v(){S().then(function(t){const r=t.map(({id:c,name:s})=>`<option value="${c}">${s}</option>`);i.insertAdjacentHTML("afterbegin",r.join("")),new m({select:i})}).catch(function(t){p()}).finally(function(){n(l,!1),n(a,!1)})}function E(t){n(a,!1),n(l,!0),n(i,!0);const r=t.currentTarget.value;$(r).then(function(c){const{url:s,breeds:e}=c[0];a.innerHTML=`
        <img class="cat-picture" src="${s}" alt="${e[0].name}" width="400" loading="lazy" />
        <div class="text-box">
          <h2>${e[0].name}</h2>
          <p>${e[0].description}</p>
          <p><b>Temperament: </b>${e[0].temperament}</p>
          <p><b>Origin: </b>${e[0].origin}</p>
        </div>`}).catch(function(c){p()}).finally(function(){n(l,!1),n(i,!0),n(a,!0)})}function p(){h.error({title:"🔻 Oops!",message:"Something went wrong! Try reloading the page!",position:"topCenter",timeout:1500}),n(l,!1),n(i,!0)}i.addEventListener("change",E);v();
//# sourceMappingURL=commonHelpers.js.map
