import{a as d,S as m,i as g}from"./assets/vendor-1d5366ac.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=i(e);fetch(e.href,n)}})();const h="live_Zuu1PB5DCXr8IC90o7QvjqwUwjyaEDC5Biv1MSecsCZxv5jxKZHuSX5mZ2ZjZp62",f="https://api.thecatapi.com/v1",y=`${f}/breeds`,b=`${f}/images/search`;d.defaults.headers.common["x-api-key"]=h;function S(){return d.get(`${y}`).then(t=>t.data)}function $(t){return d.get(`${b}?breed_ids=${t}`).then(r=>r.data)}const c=document.querySelector(".breed-select"),u=document.querySelector(".loader"),a=document.querySelector(".cat-info");function o(t,r){t.classList.toggle("ss-hidden",!r)}function v(){S().then(function(t){const r=t.map(({id:i,name:s})=>`<option value="${i}">${s}</option>`);c.insertAdjacentHTML("afterbegin",r.join("")),new m({select:c})}).catch(function(t){p()}).finally(function(){o(c,!0),o(u,!1),o(a,!0)})}function E(t){o(a,!1),o(u,!0),o(c,!0);const r=t.currentTarget.value;$(r).then(function(i){i.length===0&&(a.innerHTML="");const{url:s,breeds:e}=i[0];a.innerHTML=`
        <img src="${s}" alt="${e[0].name}" width="400" loading="lazy" />
        <div class="text-box">
          <h2>${e[0].name}</h2>
          <p>${e[0].description}</p>
          <p><b>Temperament: </b>${e[0].temperament}</p>
          <p><b>Origin: </b>${e[0].origin}</p>
        </div>`}).catch(function(i){p()}).finally(function(){o(u,!1),o(c,!0),o(a,!0)})}function p(){g.error({title:"🔻 Oops!",message:"Something went wrong! Try reloading the page!",position:"topCenter"})}c.addEventListener("change",E);v();
//# sourceMappingURL=commonHelpers.js.map
